### ISSUE TITLE
Sugestão 

### ISSUE THREAD

**Issue by pedroaf0** [idvogados/idvogados#3]
Já que o idvogados é uma organização não seria adequado que os repositórios dentro dela focem as divisões do projeto tipo: idvogados/frontend, idvogados/backend?

**Comment by bember** [comment]
@pedroaf0 acho uma boa ideia, vamos aguardar a definição do escopo amanhã e aí refazemos os repositórios de acordo. Provavelmente vai acabar sendo idvogados/frontend e idvogados/backend mesmo. Valeu!

**Comment by joffilyfe** [comment]
> @pedroaf0 acho uma boa ideia, vamos aguardar a definição do escopo amanhã e aí refazemos os repositórios de acordo. Provavelmente vai acabar sendo idvogados/frontend e idvogados/backend mesmo. Valeu!

Olá @bember, tudo bem?

Onde o escopo está sendo definido, e, como podemos participar?

**Comment by andrebts** [comment]
Olá, tentei acessar o link do slack em https://idvogados.slack.com/join/shared_invite/zt-dha6rg2f-IPqnSKbO7gphBxJz2wa~MA e não estou conseguindo entrar. Assim como o @joffilyfe gostaria de saber como posso participar.

**Comment by callesjuan** [comment]
https://join.slack.com/t/idvogados/shared_invite/zt-doceruir-6lC5K0KREQCR~hvGz7u0Rg

**Comment by rodrigondec** [comment]
Estamos tendo a reunião agora no discord.

# links
- https://docs.google.com/presentation/d/1FMjad0AfBszs8JreUAjSCjJ8hPMkFhm-iIQU59FTM_M/edit#slide=id.p
- https://www.youtube.com/watch?v=S8EqXuzjsL8

**Comment by timoteo7** [comment]
Já tem um outro projeto paralelo:
https://github.com/thr0w/idvogados
https://idvogados.firebaseapp.com

**Comment by italomarca** [comment]
@bember @rodrigondec @pedroaf0 Para o pessoal de engenharia que está tentando entrar no slack/discord/etc para acompanhar e ajudar, vai ser possível?
Vi que já existem alguns links para se juntar, mas todos expirados.

**Comment by oswagner** [comment]
Manda o link do slack novamente, tá tudo expirado!

**Comment by rodrigondec** [comment]
@italomarca @oswagner

**Comment by rodrigondec** [comment]
Esse issue não está sendo levado em consideração pela organização.

Estamos organizando fluxos para auxiliar na divisão das equipes e contribuições. Acompanhem no nosso slack.

Caso não estejam lá, temos o link na nóssa página pública https://idvogados.github.io/
