### ISSUE TITLE
Licença do software 

### ISSUE THREAD

**Issue by andrebts** [idvogados/idvogados#4]
Gostaria de discutir a licença do software. Precisamos discutir qual o proposito do projeto. Esse site [aqui](https://choosealicense.com/) é fornecido pelo Github para que se possa encontrar a melhor licença. Creio que a melhor opção para o projeto como discutido no [Greg News](https://www.youtube.com/watch?v=v3B9w6wWNQA) seria a [MIT License](https://choosealicense.com/licenses/mit/).

**Comment by hollow-legal** [comment]
A licença de software tem por objetivos estabelecer como terceiros podem utilizar o que estiver no Github. 
MIT parece ser o mais aberto e padronizado se a ideia é montar algo 100% aberto, que me parece ser a ideia.

**Comment by andrebts** [comment]
Adicionado o [pull request 6](https://github.com/idvogados/idvogados/pull/6) para adicionar o arquivo de licença. Se alguem puder aprovar, seria bom definirmos o processo de desenvolvimento como deve ser feito.

**Comment by rodrigondec** [comment]
Não tenho problemas com o MIT. 

Costumo usar geralmente a GPL3 mesmo, ela acrescenta algumas outras restrições ao MIT. 

Por exemplo se 'nosso produto' é GPL3 quem utilizar 'nosso produto' para fazer um 'novo app' ou algo assim é obrigado a disponibilizar esse 'novo app' como GPL3 também.

**Comment by yagodorea** [comment]
https://stackoverflow.com/questions/3902754/mit-vs-gpl-license
