### ISSUE TITLE
Jurídico

### ISSUE THREAD

**Issue by hollow-legal** [idvogados/idvogados#5]
Entendo que precisamos dos seguintes pontos jurídicos bem delimitados:

- Termos de Uso entregador;
- Termos de Uso Advogados;
- Política de Privacidade (adequação LGPD);
- Orientações Jurídicas para todos os advogados da plataforma terem os melhores argumentos

Vou começar pela Política de Privacidade. Quem puder começar pelos outros documentos temos como ir avançando.

**Comment by rodrigondec** [comment]
Esse issue não está sendo levado em consideração pela organização.

Estamos organizando fluxos para auxiliar na divisão das equipes e contribuições. Acompanhem no nosso slack.

Caso não estejam lá, temos o link na nóssa página pública https://idvogados.github.io/
