### ISSUE TITLE
Especialidades

### ISSUE THREAD

**Issue by andrebts** [idvogados/idvogados#7]
Para sabermos a quem recorrer caso precisemos de ajuda vamos compartilhar aqui quais são as três principais aréas que temos especialidade, listadas da que temos mais experiência para a que temos menos.

1- Desenvolvimento de Software;
2- Gestão de equipes;
3- DevOps.

**Comment by tacianosilva** [comment]
1- Desenvolvimento de Software;
2- Gestão de equipes;

**Comment by 7canim** [comment]
1 - Desenvolvimento de Software

**Comment by deniojunior** [comment]
1 - DevOps
2 - Desenvolvimento de Software - BackEnd

**PS:** Todos os links para o grupo do slack que encontrei estão expirados, podem me mandar um novo link?

**Comment by cleiver** [comment]
1 - Desenvolvimento de software
2 - Gestão

**Comment by PauloMarceloNogueira** [comment]
1 - Desenvolvimento de software
4 - QA

**Comment by nomarine** [comment]
-Desenvolvimento de Software 
-Documentação

**Comment by danilowoz** [comment]
1 - Desenvolvimento de software
Especialidade em React e React Native

**Comment by viniciusgati** [comment]
Desenvolvimento de software
ruby
nodejs
foaljs
javascript
typescript

**Comment by Padreco-lbr** [comment]
1 - Dev Mobile - Android
2 - Dev Web - React/Node
2 - DevOps

**Comment by rodrigondec** [comment]
Esse issue não está sendo levado em consideração pela organização.

Estamos organizando fluxos para auxiliar na divisão das equipes e contribuições. Acompanhem no nosso slack. 

Caso não estejam lá, temos o link na nóssa página pública https://idvogados.github.io/
